on: [workflow_dispatch]
name: Deploy to Azure Container Instance

jobs:
    build-and-deploy:
        environment: demo
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: docker.pkg.github.com
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t docker.pkg.github.com/rohitdemo/asp-vue-demo/asp-vue-demo-image .
            docker push docker.pkg.github.com/rohitdemo/asp-vue-demo/asp-vue-demo-image:latest
        
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: rohitnbdemo-asp-vue-demo
            dns-name-label: rohitnbdemo-asp-vue-demo
            image: docker.pkg.github.com/rohitdemo/asp-vue-demo/asp-vue-demo-image
            registry-login-server: docker.pkg.github.com
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: rohitnbdemo-asp-vue-demo-web-container
            location: 'west us'
            ports: 80
